### ISSUE TITLE
Support for Digital Ocean Kubernetes Cluster.

### ISSUE THREAD

**Issue by calvinndea** [bitnami/kube-prod-runtime#571] opened 2019-06-22 21:36 UTC
https://www.digitalocean.com/community/questions/bitnami-kubernetes-production-runtime-bkpr-support-for-digitalocean-kubernetes-service

I have put a query on DigitalOcean to have them review and work to have BKPR be supported in their Kubernetes Offering. 

Bitnami can review and offer a compatible offering which can be boostrapped on the DigitalOcean platform.

**Comment by andycmaj** [comment] 2019-07-23 22:44
also dupe of #309

**Comment by sameersbn** [comment] 2019-10-25 03:04
Hi! We appreciate your interest in the BKPR.

While no new features are currently planned, BKPR is under active maintenance and we plan to continue supporting newer releases of Kubernetes.

We welcome the community to engage and support the development of the project through bug fixes and code contributions.

**Comment by sameersbn** [comment] 2019-10-31 04:14
duplicate of #309

**Closed by sameersbn** 2019-10-31 04:14 UTC
Labels: enhancement
