### ISSUE TITLE
inginx ingress point default domain

### ISSUE THREAD

**Issue by meodemsao** [bitnami/kube-prod-runtime#774] opened 2020-04-13 07:43 UTC
inginx ingress always point to default domain 

```
default     ingress.extensions/nginx             example.com
```

i think this reason, when i using apex domain for another ingress -> ingress alway return 503 service unavaiable

Any body known how to disable host default inginx ingress

**Comment by javsalgar** [comment] 2020-04-13 14:46
Hi,

Thank you for using BKPR. Could you provide more information to reproduce the issue?

  - Which is the target platform you are using?
   - Which command and settings you used to install BKPR?

**Comment by meodemsao** [comment] 2020-05-18 03:07
Hi,
I using kubernetes aws 1.14
I fixed this issue by delete this default ingress

**Comment by javsalgar** [comment] 2020-05-18 09:49
Thanks for letting us know. It seems that something incorrect could be set in the DNS installation parameters. We don't see this issue in our automated tests. Let's see if other users experience the same issue.

**Comment by jjo** [comment] 2020-06-02 15:03
Looks like indeed coming from https://github.com/bitnami/kube-prod-runtime/blob/master/docs/troubleshooting.md, confirming the code (manifests) itself doesn't have any `example.com` bits.
Closing for now, @meodemsao feel free to re-open if you encounter it again -- in such case, appreciate you pasting the full command line you'd used to deploy it.

**Closed by jjo** 2020-06-02 15:03 UTC
